GET http://localhost:8080/v1/players/allenga01?isAdmin=true
Accept: application/json

###
GET http://localhost:8080/v1/players
Accept: application/json

###
GET http://localhost:8080/v1/players/aardsda01
Accept: application/json

###
POST http://localhost:8080/v1/players
Accept: application/json
Content-Type: application/json

{
  "playerId": "allenga01",
  "firstName": "GaryNew",
  "lastName": "AllensonNew",
  "birthYear": 1890,
  "birthMonth": 1,
  "birthDay": 26
}

###
PUT http://localhost:8080/v1/players/allenga01
Accept: application/json
Content-Type: application/json

###
DELETE http://localhost:8080/v1/players/allenga01
Accept: application/json
Content-Type: application/json

{
  "playerId": "allenga01",
  "firstName": "GaryNew",
  "lastName": "AllensonNew",
  "birthYear": 1890,
  "birthMonth": 1,
  "birthDay": 26
}

### Model chat
POST http://localhost:8080/v1/chat
Accept: application/json
Content-Type: application/json

{
  "model": "tinyllama",
  "prompt": "I have a restcontroller with GetMapping. How can it respond with 405 on any other methods than GET"
}

###
POST http://localhost:8080/v1/chat
Accept: application/json
Content-Type: application/json

{
  "prompt": "Hello!",
  "model": "openai"
}


###
GET http://localhost:8080/v1/chat/list-models



###
POST http://localhost:11434/api/generate
Content-Type: application/json

{"model": "tinyllama","prompt": "why is the sky blue?", "stream": false}

